"""get_swatch(inputs) -> SwatchResult. Cache first, then generate, then placeholder: always an image.

get_swatch        full path: one generation per stitch x colour x weight x fibre (cached)
get_swatch_fast   structure once in neutral grey (cached), then tint to the colour in milliseconds

Example: get_swatch({"stitch_type": "cable", "colour_hex": "#5B3E96"}).source -> "cache", "generated" or "fallback";
         get_swatch_fast({...}).source -> "tint" (or "fallback" if the grey master could not be made).
"""

from __future__ import annotations

import logging
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any

from PIL import Image

from swatch import colour, fallback
from swatch.cache import SwatchCache, cache_key
from swatch.config import CONFIG
from swatch.prompt_builder import SwatchInputs, build_prompt
from swatch.providers import ImageProvider, ImageProviderError, get_image_provider

logger = logging.getLogger("swatch")


@dataclass(kw_only=True)
class SwatchResult:
    """One swatch image plus where it came from, how long it took and how close its colour is."""

    image: Image.Image
    source: str  # "cache" | "generated" | "fallback" | "tint"
    key: str
    elapsed_ms: float
    delta_e: float
    prompt: str
    inputs: SwatchInputs
    provider: str
    tinted: bool = False
    delta_e_raw: float | None = None
    generation_ms: float | None = None  # how long the original generation took (also set on cache hits)
    error: str | None = None


def key_for(inputs: SwatchInputs | dict[str, Any], provider: ImageProvider) -> str:
    """Cache key for these inputs as generated by this provider's model and quality."""
    settings = {"model": provider.model, "quality": getattr(provider, "quality", "n/a")}
    return cache_key(_as_inputs(inputs), settings)


def get_swatch(
    inputs: SwatchInputs | dict[str, Any],
    provider: ImageProvider | None = None,
    cache: SwatchCache | None = None,
    correct_colour: bool = True,
) -> SwatchResult:
    """Cache HIT -> stored image. MISS -> generate, check ΔE (tint if over threshold), store.
    Generation failure -> placeholder in the target hex (not cached, so a retry can succeed)."""
    start = time.perf_counter()
    inputs = _as_inputs(inputs)
    provider = provider or get_image_provider()
    cache = cache or SwatchCache()
    prompt = build_prompt(inputs)
    key = key_for(inputs, provider)

    cached = cache.get(key)
    if cached:
        return _cached_result(cached, key, prompt, inputs, start)

    try:
        image, usage = provider.generate(prompt, inputs)
    except Exception as exc:  # any generation failure must still show something
        return _placeholder_result(inputs, key, prompt, provider.name, exc, start)

    return _generated_result(image, usage, inputs, key, prompt, provider, cache, correct_colour, start)


def get_swatch_fast(
    inputs: SwatchInputs | dict[str, Any],
    provider: ImageProvider | None = None,
    cache: SwatchCache | None = None,
) -> SwatchResult:
    """Structure once, colour fast: fetch/generate the grey master for this stitch/weight/fibre, then tint.
    `key` is the master's key; `elapsed_ms` covers the whole call (master lookup + tint)."""
    start = time.perf_counter()
    inputs = _as_inputs(inputs)
    master = get_swatch(_master_inputs(inputs), provider=provider, cache=cache, correct_colour=False)
    if master.source == "fallback":
        return _fast_fallback_result(inputs, master, start)
    return _tinted_result(inputs, master, start)


# --- Private helpers, in the order they are used above ---


def _as_inputs(value: SwatchInputs | dict[str, Any]) -> SwatchInputs:
    """Accept either a SwatchInputs or a plain dict of its fields."""
    return value if isinstance(value, SwatchInputs) else SwatchInputs(**value)


def _elapsed_ms(start: float) -> float:
    """Milliseconds since `start` (a time.perf_counter() value), to one decimal place."""
    return round((time.perf_counter() - start) * 1000, 1)


def _cached_result(
    cached: tuple[Image.Image, dict[str, Any]], key: str, prompt: str, inputs: SwatchInputs, start: float
) -> SwatchResult:
    """Cache HIT: the stored image, with the colour check and timing recorded when it was generated."""
    image, meta = cached
    elapsed = _elapsed_ms(start)
    logger.info("SWATCH cache=HIT key=%s… elapsed_ms=%.0f", key[:16], elapsed)
    return SwatchResult(
        image=image, source="cache", key=key, elapsed_ms=elapsed, delta_e=meta["delta_e"], prompt=prompt,
        inputs=inputs, provider=meta["provider"], tinted=meta["tinted"],
        delta_e_raw=meta["delta_e_raw"], generation_ms=meta["generation_ms"],
    )


def _placeholder_result(
    inputs: SwatchInputs, key: str, prompt: str, provider: str, exc: Exception, start: float
) -> SwatchResult:
    """The failure path must not be able to fail: a broken pattern still yields a flat target-hex square."""
    try:
        image = fallback.placeholder(inputs.stitch_type, inputs.colour_hex)
    except Exception as draw_exc:  # belt and braces: fallback.placeholder already guards itself
        logger.warning("SWATCH placeholder=flat reason=%r", f"{type(draw_exc).__name__}: {draw_exc}"[:80])
        image = fallback.flat(inputs.colour_hex)
    # Our own provider errors already carry a readable message; anything else gets its type name in front.
    if isinstance(exc, ImageProviderError):
        reason = str(exc)
    else:
        reason = f"{type(exc).__name__}: {exc}"
    elapsed = _elapsed_ms(start)
    logger.warning("SWATCH fallback=placeholder reason=%r provider=%s elapsed_ms=%.0f", reason[:100], provider, elapsed)
    return SwatchResult(
        image=image, source="fallback", key=key, elapsed_ms=elapsed,
        delta_e=colour.measure_delta_e(image, inputs.colour_hex), prompt=prompt, inputs=inputs,
        provider=provider, error=reason,
    )


def _generated_result(
    image: Image.Image,
    usage: dict[str, int] | None,
    inputs: SwatchInputs,
    key: str,
    prompt: str,
    provider: ImageProvider,
    cache: SwatchCache,
    correct_colour: bool,
    start: float,
) -> SwatchResult:
    """Cache MISS that generated: measure ΔE, tint if it is over the threshold, store, and log."""
    delta_e_raw = colour.measure_delta_e(image, inputs.colour_hex)
    delta_e = delta_e_raw
    tinted = False
    if correct_colour and delta_e_raw > CONFIG.colour.delta_e_threshold:
        image = colour.tint(image, inputs.colour_hex)
        delta_e = colour.measure_delta_e(image, inputs.colour_hex)
        tinted = True

    elapsed = _elapsed_ms(start)
    meta = {
        "inputs": inputs.model_dump(), "prompt": prompt, "provider": provider.name, "model": provider.model,
        "delta_e_raw": round(delta_e_raw, 2), "delta_e": round(delta_e, 2), "tinted": tinted,
        "generation_ms": elapsed, "quality": getattr(provider, "quality", None), "usage": usage,
        "created": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    _store(cache, key, image, meta)
    logger.info(
        "SWATCH cache=MISS key=%s… provider=%s elapsed_ms=%.0f delta_e=%.1f%s",
        key[:16], provider.name, elapsed, delta_e_raw, f" tinted->{delta_e:.1f}" if tinted else "",
    )
    return SwatchResult(
        image=image, source="generated", key=key, elapsed_ms=elapsed, delta_e=delta_e, prompt=prompt, inputs=inputs,
        provider=provider.name, tinted=tinted, delta_e_raw=delta_e_raw, generation_ms=elapsed,
    )


def _store(cache: SwatchCache, key: str, image: Image.Image, meta: dict[str, Any]) -> None:
    """Write to the cache; a failed write is logged, never raised."""
    try:
        cache.put(key, image, meta)
    except OSError as exc:  # a full disk must not hide an image we already paid for
        logger.warning("SWATCH cache=WRITE_FAILED key=%s… reason=%r", key[:16], str(exc)[:80])


def _master_inputs(inputs: SwatchInputs) -> SwatchInputs:
    """The same stitch/weight/fibre in the configured neutral-grey master colour."""
    # Constructed, not model_copy(update=...): model_copy skips validation, so a lowercase master_hex
    # in config.yaml would silently re-key the master and miss the committed image.
    return SwatchInputs(
        **inputs.model_dump() | {"colour_hex": CONFIG.colour.master_hex, "colour_name": "neutral grey"}
    )


def _fast_fallback_result(inputs: SwatchInputs, master: SwatchResult, start: float) -> SwatchResult:
    """No grey master could be made: draw the placeholder straight in the target colour."""
    image = fallback.placeholder(inputs.stitch_type, inputs.colour_hex)
    elapsed = _elapsed_ms(start)
    return SwatchResult(
        image=image, source="fallback", key=master.key, elapsed_ms=elapsed,
        delta_e=colour.measure_delta_e(image, inputs.colour_hex), prompt=master.prompt, inputs=inputs,
        provider=master.provider, error=master.error,
    )


def _tinted_result(inputs: SwatchInputs, master: SwatchResult, start: float) -> SwatchResult:
    """Tint the grey master to the target colour; flag (not hide) a tint whose ΔE is over the threshold."""
    tint_start = time.perf_counter()
    image = colour.tint(master.image, inputs.colour_hex)
    tint_ms = (time.perf_counter() - tint_start) * 1000
    elapsed = _elapsed_ms(start)
    delta_e = colour.measure_delta_e(image, inputs.colour_hex)
    threshold = CONFIG.colour.delta_e_threshold

    error = None
    if delta_e > threshold:
        error = f"delta_e {delta_e:.1f} exceeds threshold {threshold}"
        logger.warning("SWATCH tint=OFF_TARGET key=%s… delta_e=%.1f threshold=%s", master.key[:16], delta_e, threshold)
    logger.info(
        "SWATCH tint key=%s… master=%s tint_ms=%.0f elapsed_ms=%.0f delta_e=%.1f",
        master.key[:16], master.source, tint_ms, elapsed, delta_e,
    )
    return SwatchResult(
        image=image, source="tint", key=master.key, elapsed_ms=elapsed, delta_e=delta_e, prompt=master.prompt,
        inputs=inputs, provider=master.provider, tinted=True, generation_ms=master.generation_ms, error=error,
    )
